name: Build and Push Docker Image from Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Build JAR
      run: mvn clean package

    - name: Determine image tag
      id: vars
      run: |
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')
          echo "TAG=${BRANCH}" >> $GITHUB_OUTPUT
        fi


    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/briscola:latest
          ${{ secrets.DOCKER_USERNAME }}/briscola:${{ steps.vars.outputs.TAG }}


